/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamegui;

/**
 *
 * @author iqapp
 */
import gamecontroller.QuestionManager;
import gamecontroller.JeopardyGame;
import gamecontroller.PlayerManager;
import javax.swing.*;

public class MainWin extends javax.swing.JFrame {

    /**
     * Creates new form GameGUI
     */
    private JLabel[] cLabels;
    private JButton[][] qButtons;
    private final JeopardyGame gameCore;
    private final QuestionManager theQuestionManager;
    private final PlayerManager thePlayerManager;
    private final MarkBoard theMarkBoard;
    
    public MainWin(JeopardyGame gameCore) {
        initComponents();
        this.gameCore = gameCore;
        this.theQuestionManager = gameCore.getQuestionManager();
        this.thePlayerManager = gameCore.getPlayerManager();
        initButtonArray();
        initGame();
        theMarkBoard = new MarkBoard(gameCore);
        theMarkBoard.setVisible(true);
    }
    
    @Override
    public void dispose(){
        this.theMarkBoard.dispose();
        super.dispose();
    }
    
    private void showQuestionWindow(int categoryIndex, int questionIndex){
        new QuestionWin(categoryIndex, questionIndex, gameCore, this, false).setVisible(true);
        this.setVisible(false);
    }
    
    private void initButtonArray(){
        cLabels = new JLabel[5];
        qButtons = new JButton[5][5];
        
        cLabels[0] = this.c1Label;
        cLabels[1] = this.c2Label;
        cLabels[2] = this.c3Label;
        cLabels[3] = this.c4Label;
        cLabels[4] = this.c5Label;
        
        qButtons[0][0] = this.c1q1Button;
        qButtons[0][1] = this.c1q2Button;
        qButtons[0][2] = this.c1q3Button;
        qButtons[0][3] = this.c1q4Button;
        qButtons[0][4] = this.c1q5Button;
        
        qButtons[1][0] = this.c2q1Button;
        qButtons[1][1] = this.c2q2Button;
        qButtons[1][2] = this.c2q3Button;
        qButtons[1][3] = this.c2q4Button;
        qButtons[1][4] = this.c2q5Button;
        
        qButtons[2][0] = this.c3q1Button;
        qButtons[2][1] = this.c3q2Button;
        qButtons[2][2] = this.c3q3Button;
        qButtons[2][3] = this.c3q4Button;
        qButtons[2][4] = this.c3q5Button;
        
        qButtons[3][0] = this.c4q1Button;
        qButtons[3][1] = this.c4q2Button;
        qButtons[3][2] = this.c4q3Button;
        qButtons[3][3] = this.c4q4Button;
        qButtons[3][4] = this.c4q5Button;
        
        qButtons[4][0] = this.c5q1Button;
        qButtons[4][1] = this.c5q2Button;
        qButtons[4][2] = this.c5q3Button;
        qButtons[4][3] = this.c5q4Button;
        qButtons[4][4] = this.c5q5Button;
        
        
    }
    
    private void initGame(){  
        for(int i = 0; i < this.theQuestionManager.getNumberOfCategories() && i < cLabels.length; i++){
            cLabels[i].setText(theQuestionManager.getCategory(i));
            
            for(int j = 0; j < this.theQuestionManager.getNumberOfQuestions(i) && j < qButtons[i].length; j++){
                this.qButtons[i][j].setEnabled(true);
                qButtons[i][j].setText(Integer.toString(this.theQuestionManager.getWeight(i, j)));
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        c1Label = new javax.swing.JLabel();
        c1q1Button = new javax.swing.JButton();
        c1q2Button = new javax.swing.JButton();
        c1q3Button = new javax.swing.JButton();
        c1q4Button = new javax.swing.JButton();
        c1q5Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        c2Label = new javax.swing.JLabel();
        c2q1Button = new javax.swing.JButton();
        c2q2Button = new javax.swing.JButton();
        c2q3Button = new javax.swing.JButton();
        c2q4Button = new javax.swing.JButton();
        c2q5Button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        c3Label = new javax.swing.JLabel();
        c3q1Button = new javax.swing.JButton();
        c3q2Button = new javax.swing.JButton();
        c3q3Button = new javax.swing.JButton();
        c3q4Button = new javax.swing.JButton();
        c3q5Button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        c4Label = new javax.swing.JLabel();
        c4q1Button = new javax.swing.JButton();
        c4q2Button = new javax.swing.JButton();
        c4q3Button = new javax.swing.JButton();
        c4q4Button = new javax.swing.JButton();
        c4q5Button = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        c5Label = new javax.swing.JLabel();
        c5q1Button = new javax.swing.JButton();
        c5q2Button = new javax.swing.JButton();
        c5q3Button = new javax.swing.JButton();
        c5q4Button = new javax.swing.JButton();
        c5q5Button = new javax.swing.JButton();
        endButton = new javax.swing.JButton();
        pickingPlayerName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel6.setPreferredSize(new java.awt.Dimension(1800, 700));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(6, 0, 0, 10));

        c1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c1Label.setText("-");
        jPanel1.add(c1Label);

        c1q1Button.setText("-");
        c1q1Button.setEnabled(false);
        c1q1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1q1ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(c1q1Button);

        c1q2Button.setText("-");
        c1q2Button.setEnabled(false);
        c1q2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1q2ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(c1q2Button);

        c1q3Button.setText("-");
        c1q3Button.setEnabled(false);
        c1q3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1q3ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(c1q3Button);

        c1q4Button.setText("-");
        c1q4Button.setEnabled(false);
        c1q4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1q4ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(c1q4Button);

        c1q5Button.setText("-");
        c1q5Button.setEnabled(false);
        c1q5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1q5ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(c1q5Button);

        jPanel6.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(6, 0, 0, 10));

        c2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c2Label.setText("-");
        jPanel2.add(c2Label);

        c2q1Button.setText("-");
        c2q1Button.setEnabled(false);
        c2q1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2q1ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(c2q1Button);

        c2q2Button.setText("-");
        c2q2Button.setEnabled(false);
        c2q2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2q2ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(c2q2Button);

        c2q3Button.setText("-");
        c2q3Button.setEnabled(false);
        c2q3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2q3ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(c2q3Button);

        c2q4Button.setText("-");
        c2q4Button.setEnabled(false);
        c2q4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2q4ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(c2q4Button);

        c2q5Button.setText("-");
        c2q5Button.setEnabled(false);
        c2q5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2q5ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(c2q5Button);

        jPanel6.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(6, 0, 0, 10));

        c3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c3Label.setText("-");
        jPanel3.add(c3Label);

        c3q1Button.setText("-");
        c3q1Button.setEnabled(false);
        c3q1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3q1ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(c3q1Button);

        c3q2Button.setText("-");
        c3q2Button.setEnabled(false);
        c3q2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3q2ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(c3q2Button);

        c3q3Button.setText("-");
        c3q3Button.setEnabled(false);
        c3q3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3q3ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(c3q3Button);

        c3q4Button.setText("-");
        c3q4Button.setEnabled(false);
        c3q4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3q4ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(c3q4Button);

        c3q5Button.setText("-");
        c3q5Button.setEnabled(false);
        c3q5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3q5ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(c3q5Button);

        jPanel6.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridLayout(6, 0, 0, 10));

        c4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c4Label.setText("-");
        jPanel4.add(c4Label);

        c4q1Button.setText("-");
        c4q1Button.setEnabled(false);
        c4q1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4q1ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(c4q1Button);

        c4q2Button.setText("-");
        c4q2Button.setEnabled(false);
        c4q2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4q2ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(c4q2Button);

        c4q3Button.setText("-");
        c4q3Button.setEnabled(false);
        c4q3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4q3ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(c4q3Button);

        c4q4Button.setText("-");
        c4q4Button.setEnabled(false);
        c4q4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4q4ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(c4q4Button);

        c4q5Button.setText("-");
        c4q5Button.setEnabled(false);
        c4q5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4q5ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(c4q5Button);

        jPanel6.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.GridLayout(6, 0, 0, 10));

        c5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c5Label.setText("-");
        jPanel5.add(c5Label);

        c5q1Button.setText("-");
        c5q1Button.setEnabled(false);
        c5q1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5q1ButtonActionPerformed(evt);
            }
        });
        jPanel5.add(c5q1Button);

        c5q2Button.setText("-");
        c5q2Button.setEnabled(false);
        c5q2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5q2ButtonActionPerformed(evt);
            }
        });
        jPanel5.add(c5q2Button);

        c5q3Button.setText("-");
        c5q3Button.setEnabled(false);
        c5q3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5q3ButtonActionPerformed(evt);
            }
        });
        jPanel5.add(c5q3Button);

        c5q4Button.setText("-");
        c5q4Button.setEnabled(false);
        c5q4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5q4ButtonActionPerformed(evt);
            }
        });
        jPanel5.add(c5q4Button);

        c5q5Button.setText("-");
        c5q5Button.setEnabled(false);
        c5q5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5q5ButtonActionPerformed(evt);
            }
        });
        jPanel5.add(c5q5Button);

        jPanel6.add(jPanel5);

        endButton.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        endButton.setLabel("End");
        endButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endButtonActionPerformed(evt);
            }
        });

        pickingPlayerName.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        pickingPlayerName.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pickingPlayerName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(endButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(pickingPlayerName)
                .addGap(49, 49, 49)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(endButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //this.setExtendedState(Frame.MAXIMIZED_BOTH);
        this.pickingPlayerName.setText(thePlayerManager.getPlayerName(thePlayerManager.getAnsweringPlayerIndex()) + ", please pick a question");
    }//GEN-LAST:event_formWindowActivated

    private void c1q1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1q1ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(0, 0);
    }//GEN-LAST:event_c1q1ButtonActionPerformed

    private void c2q1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2q1ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(1, 0);
    }//GEN-LAST:event_c2q1ButtonActionPerformed

    private void c2q4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2q4ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(1, 3);
    }//GEN-LAST:event_c2q4ButtonActionPerformed

    private void c2q5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2q5ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(1, 4);
    }//GEN-LAST:event_c2q5ButtonActionPerformed

    private void c3q1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3q1ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(2, 0);
    }//GEN-LAST:event_c3q1ButtonActionPerformed

    private void c4q1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4q1ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(3, 0);
    }//GEN-LAST:event_c4q1ButtonActionPerformed

    private void c5q1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5q1ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(4, 0);
    }//GEN-LAST:event_c5q1ButtonActionPerformed

    private void c1q2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1q2ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(0, 1);
    }//GEN-LAST:event_c1q2ButtonActionPerformed

    private void c1q3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1q3ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(0, 2);
    }//GEN-LAST:event_c1q3ButtonActionPerformed

    private void c1q4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1q4ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(0, 3);
    }//GEN-LAST:event_c1q4ButtonActionPerformed

    private void c1q5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1q5ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(0, 4);
    }//GEN-LAST:event_c1q5ButtonActionPerformed

    private void c2q2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2q2ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(1, 1);
    }//GEN-LAST:event_c2q2ButtonActionPerformed

    private void c2q3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2q3ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(1, 2);
    }//GEN-LAST:event_c2q3ButtonActionPerformed

    private void c3q2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3q2ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(2, 1);
    }//GEN-LAST:event_c3q2ButtonActionPerformed

    private void c3q3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3q3ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(2, 2);
    }//GEN-LAST:event_c3q3ButtonActionPerformed

    private void c3q4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3q4ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(2, 3);
    }//GEN-LAST:event_c3q4ButtonActionPerformed

    private void c3q5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3q5ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(2, 4);
    }//GEN-LAST:event_c3q5ButtonActionPerformed

    private void c4q2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4q2ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(3, 1);
    }//GEN-LAST:event_c4q2ButtonActionPerformed

    private void c4q3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4q3ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(3, 2);
    }//GEN-LAST:event_c4q3ButtonActionPerformed

    private void c4q4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4q4ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(3, 3);
    }//GEN-LAST:event_c4q4ButtonActionPerformed

    private void c4q5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4q5ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(3, 4);
    }//GEN-LAST:event_c4q5ButtonActionPerformed

    private void c5q2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5q2ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(4, 1);
    }//GEN-LAST:event_c5q2ButtonActionPerformed

    private void c5q3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5q3ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(4, 2);
    }//GEN-LAST:event_c5q3ButtonActionPerformed

    private void c5q4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5q4ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(4, 3);
    }//GEN-LAST:event_c5q4ButtonActionPerformed

    private void c5q5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5q5ButtonActionPerformed
        // TODO add your handling code here:
        questionButtonAction(4, 4);
    }//GEN-LAST:event_c5q5ButtonActionPerformed

    private void endButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endButtonActionPerformed
        // TODO add your handling code here:
        this.gameCore.end();
        new FameHallWin(this.gameCore).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_endButtonActionPerformed

    private void showDoubleWindow(int categoryIndex, int questionIndex){
        new BetWin(categoryIndex, questionIndex, gameCore, this).setVisible(true);
        this.setVisible(false);
    }
    
    private void questionButtonAction(int categoryIndex, int questionIndex){
        if(this.theQuestionManager.isDoubleJeopardy(categoryIndex, questionIndex))
            showDoubleWindow(categoryIndex, questionIndex);
        else
            showQuestionWindow(categoryIndex, questionIndex);
        
        this.qButtons[categoryIndex][questionIndex].setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c1Label;
    private javax.swing.JButton c1q1Button;
    private javax.swing.JButton c1q2Button;
    private javax.swing.JButton c1q3Button;
    private javax.swing.JButton c1q4Button;
    private javax.swing.JButton c1q5Button;
    private javax.swing.JLabel c2Label;
    private javax.swing.JButton c2q1Button;
    private javax.swing.JButton c2q2Button;
    private javax.swing.JButton c2q3Button;
    private javax.swing.JButton c2q4Button;
    private javax.swing.JButton c2q5Button;
    private javax.swing.JLabel c3Label;
    private javax.swing.JButton c3q1Button;
    private javax.swing.JButton c3q2Button;
    private javax.swing.JButton c3q3Button;
    private javax.swing.JButton c3q4Button;
    private javax.swing.JButton c3q5Button;
    private javax.swing.JLabel c4Label;
    private javax.swing.JButton c4q1Button;
    private javax.swing.JButton c4q2Button;
    private javax.swing.JButton c4q3Button;
    private javax.swing.JButton c4q4Button;
    private javax.swing.JButton c4q5Button;
    private javax.swing.JLabel c5Label;
    private javax.swing.JButton c5q1Button;
    private javax.swing.JButton c5q2Button;
    private javax.swing.JButton c5q3Button;
    private javax.swing.JButton c5q4Button;
    private javax.swing.JButton c5q5Button;
    private javax.swing.JButton endButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel pickingPlayerName;
    // End of variables declaration//GEN-END:variables
}
