/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamegui;

import gamecontroller.*;
import java.util.Observable;
import java.util.Observer;
import javax.swing.*;
import java.util.ArrayList;
/**
 *
 * @author student
 */
public class MarkBoard extends javax.swing.JFrame implements  Observer{

    /**
     * Creates new form markBoard
     */
    private PlayerManager thePlayerManager;
    private ArrayList<JLabel> playerNameMarks;
    
    public MarkBoard(JeopardyGame gameCore) {
        initComponents();
        
        this.thePlayerManager = gameCore.getPlayerManager();
        this.thePlayerManager.addObserver(this);
        playerNameMarks = new ArrayList();
        putPlayers();
    }

    public void putPlayers(){
        ArrayList<Player> players = this.thePlayerManager.getCurrentOrderedPlayers();
        
        for(Player player : players){
            JLabel playerLabel = new JLabel();
            playerLabel.setText(player.name + ": " + player.mark);
            playerLabel.setFont(new java.awt.Font("Lucida Grande", 0, 36)); 
            this.markPanel.add(playerLabel);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        markPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(400, 400));
        jScrollPane2.setSize(new java.awt.Dimension(400, 400));

        markPanel.setLayout(new javax.swing.BoxLayout(markPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(markPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update(Observable o, Object arg){
        this.markPanel.removeAll();
        putPlayers();
        this.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel markPanel;
    // End of variables declaration//GEN-END:variables
}
