/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamegui;

import gamemodal.*;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/**
 *
 * @author student
 */

public class QuestionWin extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form QuestionWin
     */
    private final QuestionManager theQuestionManager;
    private final PlayerManager thePlayerManager;
    private final MainWin theMainWindow;
    private final String answer;
    private final int weight;
    private final Timer theTimer;
    private int time;
    private boolean ignoreInput;
    
    public QuestionWin(int categoryIndex, int questionIndex, JeopardyGame gameCore, MainWin theMainWindow) {
        initComponents();
        theQuestionManager = gameCore.getQuestionManager();
        thePlayerManager = gameCore.getPlayerManager();
        this.theMainWindow = theMainWindow;      
        this.qaTextArea.setText(theQuestionManager.getQuestion(categoryIndex, questionIndex));
        this.answer = this.theQuestionManager.getAnswer(categoryIndex, questionIndex);
        this.weight = theQuestionManager.getWeight(categoryIndex, questionIndex);
        this.time = 30;
        this.timeLabel.setText(Integer.toString(time));
        this.theTimer = new Timer(1000, this);
        ignoreInput = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        answerButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        qaTextArea = new javax.swing.JTextArea();
        rightButton = new javax.swing.JButton();
        wrongButton = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        answeringName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        answerButton.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        answerButton.setToolTipText("");
        answerButton.setAutoscrolls(true);
        answerButton.setEnabled(false);
        answerButton.setLabel("Answer");
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });

        qaTextArea.setColumns(20);
        qaTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        qaTextArea.setLineWrap(true);
        qaTextArea.setRows(5);
        qaTextArea.setFocusable(false);
        jScrollPane2.setViewportView(qaTextArea);

        rightButton.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        rightButton.setText("Right");
        rightButton.setEnabled(false);
        rightButton.setPreferredSize(new java.awt.Dimension(200, 66));
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });

        wrongButton.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        wrongButton.setText("Wrong");
        wrongButton.setEnabled(false);
        wrongButton.setPreferredSize(new java.awt.Dimension(200, 66));
        wrongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrongButtonActionPerformed(evt);
            }
        });

        timeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        timeLabel.setText("Time");

        answeringName.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        answeringName.setText("Please type your key");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(447, Short.MAX_VALUE)
                .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                .addComponent(wrongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(449, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(answeringName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(answerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(answeringName)
                .addGap(18, 18, 18)
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(answerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    public void actionPerformed(ActionEvent e){
        if(this.time == 1)
            timeUp();
        else
            this.timeLabel.setText(Integer.toString(--this.time));
    }
    
    private void timeUp(){
        this.theTimer.stop();
        this.timeLabel.setText("Sorry, time is up. The answer is");
        this.qaTextArea.setText(answer);
        this.rightButton.setEnabled(false);
        this.answerButton.setEnabled(false);
    }
    
    private void changeMark(int offset){
        this.thePlayerManager.changeMark(offset);
        this.theMainWindow.setVisible(true);
        this.dispose();
    }
    
    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed
        // TODO add your handling code here:
        this.qaTextArea.setText(answer);
    }//GEN-LAST:event_answerButtonActionPerformed

    private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
        // TODO add your handling code here:
        this.changeMark(this.weight);
    }//GEN-LAST:event_rightButtonActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
        if(!ignoreInput && thePlayerManager.setAnsweringPlayer(evt.getKeyChar())){
            this.ignoreInput = true;
            this.answerButton.setEnabled(true);
            this.rightButton.setEnabled(true);
            this.wrongButton.setEnabled(true);
            this.answeringName.setText(thePlayerManager.getAnsweringPlayerName());
            this.theTimer.start();
        }
    }//GEN-LAST:event_formKeyTyped

    private void wrongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrongButtonActionPerformed
        // TODO add your handling code here:
        this.changeMark(-this.weight);
    }//GEN-LAST:event_wrongButtonActionPerformed
  
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JLabel answeringName;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea qaTextArea;
    private javax.swing.JButton rightButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JButton wrongButton;
    // End of variables declaration//GEN-END:variables
}
