/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamegui;

import gamemodal.*;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/**
 *
 * @author student
 */

public class QuestionWin extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form QuestionWin
     */
    private final QuestionManager theQuestionManager;
    private final PlayerManager thePlayerManager;
    private final MainWin theMainWindow;
    private final String answer;
    private final int weight;
    private final Timer theTimer;
    private final int defaultTime = 30;
    private int time;
    private boolean ignoreInput;
    private boolean isShowingAnswer;
    
    public QuestionWin(int categoryIndex, int questionIndex, JeopardyGame gameCore, MainWin theMainWindow) {
        initComponents();
        theQuestionManager = gameCore.getQuestionManager();
        thePlayerManager = gameCore.getPlayerManager();
        this.theMainWindow = theMainWindow;      
        this.qaTextArea.setText(theQuestionManager.getQuestion(categoryIndex, questionIndex));
        this.answer = this.theQuestionManager.getAnswer(categoryIndex, questionIndex);
        this.weight = theQuestionManager.getWeight(categoryIndex, questionIndex);
        this.time = defaultTime;
        this.timeLabel.setText(Integer.toString(time));
        this.theTimer = new Timer(1000, this);
        ignoreInput = false;
        isShowingAnswer = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        answerButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        qaTextArea = new javax.swing.JTextArea();
        rightButton = new javax.swing.JButton();
        wrongButton = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        answeringName = new javax.swing.JLabel();
        goBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        answerButton.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        answerButton.setToolTipText("");
        answerButton.setAutoscrolls(true);
        answerButton.setEnabled(false);
        answerButton.setLabel("Answer");
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });

        qaTextArea.setColumns(20);
        qaTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        qaTextArea.setLineWrap(true);
        qaTextArea.setRows(5);
        qaTextArea.setFocusable(false);
        qaTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qaTextAreaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(qaTextArea);

        rightButton.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        rightButton.setText("Right");
        rightButton.setEnabled(false);
        rightButton.setPreferredSize(new java.awt.Dimension(200, 66));
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });

        wrongButton.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        wrongButton.setText("Wrong");
        wrongButton.setEnabled(false);
        wrongButton.setPreferredSize(new java.awt.Dimension(200, 66));
        wrongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrongButtonActionPerformed(evt);
            }
        });

        timeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("Time");

        answeringName.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        answeringName.setText("Please type your key");

        goBackButton.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        goBackButton.setText("Give Up");
        goBackButton.setPreferredSize(new java.awt.Dimension(200, 66));
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wrongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(45, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1573, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(answeringName)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(answerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(651, 651, 651)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(answeringName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(timeLabel)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(answerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    public void actionPerformed(ActionEvent e){
        if(this.time == 1)
            timeUp();
        else
            this.timeLabel.setText(Integer.toString(--this.time));
    }
    
    private void timeUp(){
        this.theTimer.stop();
        this.timeLabel.setText("Sorry, time is up. The answer is");
        this.qaTextArea.setText(answer);
        this.rightButton.setEnabled(false);
        this.answerButton.setEnabled(false);
    }
    
    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed
        // TODO add your handling code here:
        this.isShowingAnswer = true;
        this.qaTextArea.setText(answer + "\n[Click here to go back]");
    }//GEN-LAST:event_answerButtonActionPerformed

    private void showMainWindow(){
        this.thePlayerManager.clearForbiddenPlayers();
        theMainWindow.setVisible(true);
        this.dispose();
    }
    private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
        // TODO add your handling code here:
        this.thePlayerManager.right(weight);
        this.showMainWindow();
    }//GEN-LAST:event_rightButtonActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
        if(!ignoreInput && thePlayerManager.setAnsweringPlayer(evt.getKeyChar())){
            this.ignoreInput = true;
            this.goBackButton.setEnabled(false);
            this.answerButton.setEnabled(true);
            this.rightButton.setEnabled(true);
            this.wrongButton.setEnabled(true);
            this.answeringName.setText(thePlayerManager.getAnsweringPlayerName());
            this.theTimer.start();
        }
    }//GEN-LAST:event_formKeyTyped

    private void reset(){
        this.theTimer.stop();
        this.time = this.defaultTime;
        this.timeLabel.setText(Integer.toString(this.time));
        this.ignoreInput = false;
        this.timeLabel.setText(Integer.toString(this.time));
        this.rightButton.setEnabled(false);
        this.answerButton.setEnabled(false);
        this.wrongButton.setEnabled(false);
        this.goBackButton.setEnabled(true);
        this.requestFocus();
    }
    
    private void wrongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrongButtonActionPerformed
        // TODO add your handling code here:
        this.thePlayerManager.wrong(-weight);
        if(thePlayerManager.numberOfAllowablePlayers() == 0){
            this.answerButtonActionPerformed(null);
        }
        else{
            this.answeringName.setText("Anyone else?");
            reset();
        }
    }//GEN-LAST:event_wrongButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:
        this.showMainWindow();
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void qaTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qaTextAreaMouseClicked
        // TODO add your handling code here:
        if(isShowingAnswer){
            this.showMainWindow();
        }
    }//GEN-LAST:event_qaTextAreaMouseClicked
  
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JLabel answeringName;
    private javax.swing.JButton goBackButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea qaTextArea;
    private javax.swing.JButton rightButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JButton wrongButton;
    // End of variables declaration//GEN-END:variables
}
