/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeopardygame.controller;

import jeopardygame.exception.DuplicateNameException;
import jeopardygame.exception.EmptyPlayerNameException;
import jeopardygame.exception.EmptyPlayerKeyException;
import jeopardygame.exception.DuplicateKeyException;
import jeopardygame.visualeffect.JeopardyColors;
import jeopardygame.model.JeopardyGame;
import jeopardygame.model.Player;
import java.io.IOException;
import java.util.Observer;
import java.util.Observable;
import jeopardygame.constant.*;
import jeopardygame.exception.NotEnoughPlayersException;
/**
 *
 * @author iqapp
 */
public class AddPlayerWin extends javax.swing.JFrame implements  Observer{

    /**
     * Creates new form AddPlayerWin
     */
    private int currentPlayerIndex;
    private final String titleMessagePrefix;
    private final String warningMessagePrefix;
    private final JeopardyGame gameCore;   
    
    public AddPlayerWin(JeopardyGame gameCore) {
        initComponents();
        currentPlayerIndex = 0;
        titleMessagePrefix = "Total players: ";
        warningMessagePrefix = "Can't start game: ";
        this.gameCore = gameCore;
        
        JeopardyColors.setComponentColor(this.rootPane);
        this.setTitle(titleMessagePrefix + gameCore.getNumOfCurrentPlayers());
        this.resetNameTextField();
        this.resetKeyTextField();
        this.gameCore.addObserver(this);
    }
    
    @Override
    public void dispose(){
        if(!gameCore.isStarted()){
            gameCore.end();
            new FameHallWin(this.gameCore).setVisible(true);
        }
        
        this.gameCore.deleteObservers();
        super.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nameTextField = new javax.swing.JTextField();
        keyTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        prevButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("key:");
        jPanel1.add(jLabel2);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        nameTextField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });
        nameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTextFieldMouseClicked(evt);
            }
        });
        jPanel2.add(nameTextField);

        keyTextField.setEditable(false);
        keyTextField.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        keyTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        keyTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyTextFieldKeyTyped(evt);
            }
        });
        jPanel2.add(keyTextField);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 50, 0));

        prevButton.setText("Prev");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });
        jPanel3.add(prevButton);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel3.add(startButton);

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel3.add(nextButton);

        warningLabel.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(warningLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(warningLabel)
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTextFieldMouseClicked
        // TODO add your handling code here:
        this.warningLabel.setText("");
    }//GEN-LAST:event_nameTextFieldMouseClicked

    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
        // TODO add your handling code here:
        this.nameTextField.selectAll();
    }//GEN-LAST:event_nameTextFieldFocusGained
        
    private void addPlayer() throws DuplicateNameException, DuplicateKeyException, EmptyPlayerNameException, EmptyPlayerKeyException{
        if(this.keyTextField.getText().equals(""))
            throw new EmptyPlayerKeyException();
        
        Player newPlayer = new Player(this.nameTextField.getText(), this.keyTextField.getText().charAt(0), Constants.INITIAL_CREDITS, this.currentPlayerIndex);
        gameCore.addPlayer(newPlayer);
        
    }
    
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        this.warningLabel.setText("");
        try{
            this.addPlayer();
            this.currentPlayerIndex++;
            this.displayPlayer();
            
        }catch(DuplicateNameException e){
            this.nameTextField.selectAll();
            this.warningLabel.setText("Name exits, please use a different name");
        }catch(DuplicateKeyException e){
            this.resetKeyTextField();
            this.warningLabel.setText("Key exits, please choose a new one");
            this.keyTextField.requestFocus();
        }catch(EmptyPlayerNameException e){
            this.nameTextField.requestFocus();
            this.warningLabel.setText("Please enter your name");
        }catch(EmptyPlayerKeyException e){
            this.resetKeyTextField();
            this.warningLabel.setText("Please press a key");
            this.keyTextField.requestFocus();
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldFocusLost

    private void displayPlayer(){
        if(this.currentPlayerIndex < gameCore.getNumOfCurrentPlayers()){
            Player thePlayer = gameCore.getPlayer(this.currentPlayerIndex);
            this.nameTextField.setText(thePlayer.getName());
            this.keyTextField.setText(Character.toString(thePlayer.getKey()));
        }else{
            this.resetKeyTextField();
            this.resetNameTextField();
        }
            
    }
    
    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        // TODO add your handling code here: 
        this.warningLabel.setText("");
        try{
            if(!this.nameTextField.getText().equals("") || !this.keyTextField.getText().equals(""))
                this.addPlayer();
            else{
                if(this.currentPlayerIndex > 0){
                    this.currentPlayerIndex--;
                    this.displayPlayer();
                }
            }   
        }catch(DuplicateNameException e){
            this.nameTextField.selectAll();
            this.warningLabel.setText("Name exits, please use a different name");
        }catch(DuplicateKeyException e){
            this.resetKeyTextField();
            this.warningLabel.setText("Key exits, please choose a new one");
            this.keyTextField.requestFocus();
        }catch(EmptyPlayerNameException e){
            this.nameTextField.requestFocus();
            this.warningLabel.setText("Please enter your name");
        }catch(EmptyPlayerKeyException e){
            this.resetKeyTextField();
            this.warningLabel.setText("Please press a key");

            this.keyTextField.requestFocus();
        }
        

    }//GEN-LAST:event_prevButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        this.warningLabel.setText("");
        try{
            if(!this.nameTextField.getText().equals("") || !this.keyTextField.getText().equals(""))
                this.addPlayer();

            this.startGame();
        }catch(DuplicateNameException e){
            this.nameTextField.selectAll();
            this.warningLabel.setText("Name exits, please use a different name");
        }catch(DuplicateKeyException e){
            this.resetKeyTextField();
            this.warningLabel.setText("Key exits, please choose a new one");
            this.keyTextField.requestFocus();
        }catch(EmptyPlayerNameException e){
            this.nameTextField.requestFocus();
            this.warningLabel.setText("Please enter your name");
        }catch(EmptyPlayerKeyException e){
            this.resetKeyTextField();
            this.warningLabel.setText("Please press a key");

            this.keyTextField.requestFocus();
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void startGame(){
        try{
            this.gameCore.start("Question0");
            new MainWin(this.gameCore).setVisible(true);
            this.dispose();
        }catch(NotEnoughPlayersException | IOException e){
            this.warningLabel.setText(this.warningMessagePrefix + e.getMessage());
        }catch(ClassNotFoundException e){
            this.warningLabel.setText(this.warningMessagePrefix + "It is not a question file");
        }
    }
    private void keyTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyTextFieldKeyTyped
        // TODO add your handling code here:
        this.keyTextField.setText(Character.toString(evt.getKeyChar()));
        this.warningLabel.setText("");
    }//GEN-LAST:event_keyTextFieldKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        System.out.println("IM OPend");
    }//GEN-LAST:event_formWindowOpened

    private void resetNameTextField(){
        this.nameTextField.setText(""); 
        this.nameTextField.requestFocus();
    }
    
    private void resetKeyTextField(){
        this.keyTextField.setText("");
    }
    
    @Override
    public void update(Observable o, Object arg){
        this.setTitle(titleMessagePrefix + (int)arg);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField keyTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
